/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {

    public static void main(String[] args) {
        var data = InputReader.readInput();
        int[] arr = data.array();
        int[] queries = data.queries();
        float alpha = Float.parseFloat(args[0]);
        SearchTree st = new SearchTree(arr, alpha);
        for (int i = 0; i < queries.length; i++) {
            System.out.println(st.Pred(queries[i]));
        }

    }
}
