/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

public class Main {

    public static void main(String[] args) {
        if (args.length < 2) {
            System.out.println("Usage: java Main <ImplementationName> <AlphaValue>");
            return;
        }
        var data = InputReader.readInput();
        int[] arr = data.array(); // An array of distinct random integers
        int[] queries = data.queries(); // An array of random integers to query the implementations
        float alpha = Float.parseFloat(args[1]);

        SkewedBinarySearchTree tree = null;

        if (args[0].equals("SortedArrayBinarySearch")) {
            tree = new SortedArrayBinarySearch(arr, alpha);
        }
        if (args[0].equals("SearchTree")) {
            tree = new SearchTree(arr, alpha);
        }

        if (args[0].equals("OtherArrayBinarySearch")) {
            tree = new OtherArrayBinarySearch(arr, alpha);
        }
        if (args[0].equals("KArrayBinarySearch")) {
            tree = new KArrayBinarySearch(arr, alpha, 2);
        }

        if (tree == null) {
            throw new Error("Ensure the implementation is correctly added");
        }

        // Warm up
        for (int i = 0; i < 10_000; i++) {
            tree.pred(queries[i % queries.length]);
        }

        long start = System.nanoTime();
        for (int i = 0; i < queries.length; i++) {
            tree.pred(queries[i]);
        }
        long end = System.nanoTime();
        System.out.println(end - start);
    }

}
