/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rank_select;

import org.junit.Test;
import static org.junit.Assert.*;

public class RankSelectNaiveTest {
    @Test public void testRankBasic_1() {
        int[] ranksData = new int[] {
            0, // 0 index 1
            0, // 0 
            1, // 1 index 2
            0, // 1
            0, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectNaive rs = new RankSelectNaive(ranksData);

        assertTrue((rs.rank(0) == 0));
        assertTrue(rs.rank(1) == 0);
        assertTrue(rs.rank(2) == 1);
        assertTrue(rs.rank(3) == 1);
        assertTrue(rs.rank(4) == 1);
        assertTrue(rs.rank(5) == 2);
        assertTrue(rs.rank(6) == 3);
        assertTrue(rs.rank(7) == 4);
        assertTrue(rs.rank(8) == 4);
        assertTrue(rs.rank(9) == 4);
    }


    @Test public void testRankBasic_All_Zeros() {
        int[] ranksData = new int[] {
            0, // 0 index 1
            0, // 0 
            0, // 1 index 2
            0, // 1
            0, // 1
            0, // 2 index 5
            0, // 3 index 6
            0, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectNaive rs = new RankSelectNaive(ranksData);

        for(int i = 0; i < ranksData.length; i++) {
            assertTrue((rs.rank(i) == 0));
        }
    }

    @Test public void testRankBasic_All_Ones() {
        int[] ranksData = new int[] {
            1, // 0 index 1
            1, // 0 
            1, // 1 index 2
            1, // 1
            1, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            1, // 4 
            1, // 4
        };
        RankSelectNaive rs = new RankSelectNaive(ranksData);

        for(int i = 0; i < ranksData.length; i++) {
            assertTrue((rs.rank(i) == i + 1));
        }
    }


    @Test public void testRankBasic_OutOfBounds() {
        int[] ranksData = new int[] {
            1, // 0 index 1
            1, // 0 
            1, // 1 index 2
            1, // 1
            1, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            1, // 4 
            1, // 4
        };
        RankSelectNaive rs = new RankSelectNaive(ranksData);

        try {
            assertNull((Integer)rs.rank(-5)); // Should never occur
        } catch (Exception e) {
            assertTrue(true);
        }

        try {
            assertNull((Integer)rs.rank(ranksData.length)); // Should never occur
        } catch (Exception e) {
            assertTrue(true);
        }

        for(int i = 0; i < ranksData.length; i++) {
            assertTrue((rs.rank(i) == i + 1));
        }
    }
}
