/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rank_select;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * The rank tests are more than sufficent as they tests all the boundaries
 * i.e. the different branches of the rank method that is the if statements.
 * 
 * The select tests covers all the branches of the naive select implementation.
 */
public class RankSelectLookupHashMapTest {
    @Test public void testRankBasic_1() throws Exception {
        int[] ranksData = new int[] {
            0, // 0 index 1
            0, // 0 
            1, // 1 index 2
            0, // 1
            0, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);

        assertTrue((rs.rank(0) == 0));
        assertTrue(rs.rank(1) == 0);
        assertTrue(rs.rank(2) == 1);
        assertTrue(rs.rank(3) == 1);
        assertTrue(rs.rank(4) == 1);
        assertTrue(rs.rank(5) == 2);
        assertTrue(rs.rank(6) == 3);
        assertTrue(rs.rank(7) == 4);
        assertTrue(rs.rank(8) == 4);
        assertTrue(rs.rank(9) == 4);
    }


    @Test public void testRankBasic_All_Zeros() throws Exception {
        int[] ranksData = new int[] {
            0, // 0 index 1
            0, // 0 
            0, // 1 index 2
            0, // 1
            0, // 1
            0, // 2 index 5
            0, // 3 index 6
            0, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);

        for(int i = 0; i < ranksData.length; i++) {
            assertTrue((rs.rank(i) == 0));
        }
    }

    @Test public void testRankBasic_All_Ones() throws Exception {
        int[] ranksData = new int[] {
            1, // 0 index 1
            1, // 0 
            1, // 1 index 2
            1, // 1
            1, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            1, // 4 
            1, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);
        
        for(int i = 0; i < ranksData.length; i++) {
            assertTrue((rs.rank(i) == i + 1));
        }
    }


    @Test public void testRankBasic_OutOfBounds() {
        int[] ranksData = new int[] {
            1, // 0 index 1
            1, // 0 
            1, // 1 index 2
            1, // 1
            1, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            1, // 4 
            1, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);

        try {
            assertNull((Integer)rs.rank(-5)); // Should never occur
        } catch (Exception e) {
            assertTrue(true);
        }

        try {
            assertNull((Integer)rs.rank(ranksData.length)); // Should never occur
        } catch (Exception e) {
            assertTrue(true);
        }

        try{
            for(int i = 0; i < ranksData.length; i++) {
                assertTrue((rs.rank(i) == i + 1));
            }
        } catch(Exception e) {
            assertTrue(false); // Should never happen
        }
        
    }

    //////////////////////////////////
    /// Testing the select method ///
    ////////////////////////////////
    
    @Test
    public void testSelect_EmptyArray() throws Exception {
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(new int[0]);
        assertTrue(rs.select(0) == -1);
    }

    @Test public void testSelectBasic_1() {
        int[] ranksData = new int[] {
            0, // 0 index 1
            0, // 0 
            1, // 1 index 2
            0, // 1
            0, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);

        assertTrue((rs.select(0) == 0)); // Acounts for the second if statement
        assertTrue(rs.select(1) == 2);
        assertTrue(rs.select(2) == 5);
        assertTrue(rs.select(3) == 6);
        assertTrue(rs.select(4) == 7);
    }


    @Test public void testSelectBasic_MissCase_1() {
        int[] ranksData = new int[] {
            1, // 0 index 1
            0, // 0 
            1, // 1 index 2
            0, // 1
            0, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);

        assertTrue((rs.select(0) == -1)); // Acounts for the third if statement
        assertTrue((rs.select(1) == 0));
        assertTrue(rs.select(2) == 2);
        assertTrue(rs.select(3) == 5);
        assertTrue(rs.select(4) == 6);
        assertTrue(rs.select(5) == 7);
    }

    @Test public void testSelectBasic_MissCase_2() {
        int[] ranksData = new int[] {
            1, // 0 index 1
            0, // 0 
            1, // 1 index 2
            0, // 1
            0, // 1
            1, // 2 index 5
            1, // 3 index 6
            1, // 4 index 7
            0, // 4 
            0, // 4
        };
        RankSelectLookupHashMap rs = new RankSelectLookupHashMap(ranksData);

        assertTrue((rs.select(0) == -1)); // Acounts for the third if statement
        assertTrue((rs.select(1) == 0));
        assertTrue(rs.select(2) == 2);
        assertTrue(rs.select(3) == 5);
        assertTrue(rs.select(4) == 6);
        assertTrue(rs.select(5) == 7);
        assertTrue(rs.select(6) == -1); // Acounts for a rank not in the array
    }
}
